Update readme to make metrics more clear
TonicAI/tonic_validate pull request #89
Opened 2024-03-08 19:21 UTC by ethan-tonic

Makes it more clear that the metrics we list are not the only ones in Tonic Validate.

2024-03-08 19:26 UTC, ethan-tonic commented on README.md
> +#### **Run Time**
Added this in since we mention the run time metric in the table

2024-03-08 23:01 UTC, akamor commented on README.md
> +Metrics are used to score your LLM's performance.  Validate ships with 6 metrics which are applicable to most RAG systems.  You can create your own metrics as well by providing your own implementatio
"Validate ships with 6 metrics...."

This is no longer true.  I think we remove that number and make it more generic.

2024-03-08 23:02 UTC, akamor requested changes
See comments. Otherwise good.

2024-03-14 14:27 UTC, akamor approved these changes

2024-03-14 14:28 UTC, merged